version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    volumes:
      - ./app:/var/www/html/app
    ports:
      - 8000:80
    env_file:
        - ./docker/apache/.env
    networks:
      - default
  db:
    image: mysql:8.0.21
    volumes:
        - ./docker/db/my.cnf:/etc/mysql/conf.d/custom.cnf
        - db-data:/var/lib/mysql
        - ./docker/db/initdb:/docker-entrypoint-initdb.d/
    env_file:
        - ./docker/db/.env
    networks:
      - default

volumes:
  db-data:
    external: false

networks:
  default:
