version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    volumes:
      - ./app:/var/www/html/app
    ports:
      - 8000:80
    env_file:
        - ./docker/apache/.env
  db:
    image: mysql:5.5.54
    volumes:
        - db-data:/var/lib/mysql
        - ./docker/db/initdb:/docker-entrypoint-initdb.d/
    env_file:
        - ./docker/db/.env

volumes:
  db-data:
    external: false
